// Auto-generated
let project = new Project('police_ai');

project.addSources('Sources');
project.addLibrary("C:/Games/Armory_05_win64_b27/Armory/armsdk/armory");
project.addLibrary("C:/Games/Armory_05_win64_b27/Armory/armsdk/iron");
project.addLibrary("C:/Games/Armory_05_win64_b27/Armory/armsdk/lib/haxebullet");
project.addAssets("C:/Games/Armory_05_win64_b27/Armory/armsdk/lib/haxebullet/js/ammo/ammo.js", { notinlist: true });
project.addParameter('-dce full');
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('arm.PoliceAI');
project.addParameter("--macro keep('arm.PoliceAI')");
project.addParameter('arm.Player');
project.addParameter("--macro keep('arm.Player')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/car_mesh.frag.glsl");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/car_mesh.vert.glsl");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/ground_mesh.frag.glsl");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/home1_mesh.frag.glsl");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/home2_mesh.frag.glsl");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/home3_mesh.frag.glsl");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/home4_mesh.frag.glsl");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/home5_mesh.frag.glsl");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/police_mesh.frag.glsl");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/terrain_mesh.frag.glsl");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/w_mesh.frag.glsl");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/world_pass.frag.glsl");
project.addShaders("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/world_pass.vert.glsl");
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/car_data.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/ground_data.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/home1_data.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/home2_data.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/home3_data.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/home4_data.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/home5_data.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/police_data.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/shader_datas.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/terrain_data.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Shaders/w_data.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("Bundled/config.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/Armory_05_win64_b27/Armory/armsdk/armory/Assets/brdf.png", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/Scene.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/envmaps/World_irradiance.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.001.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.003.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.004.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.005.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.007.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.008.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.009.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.010.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.014.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.015.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.029.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.061.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.062.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.063.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.064.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.065.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.066.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.067.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cube.068.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cylinder.004.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cylinder.005.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Cylinder.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("C:/Games/armory_templates_ai/police_ai/build_police_ai/compiled/Assets/meshes/mesh_Plane.arm", { notinlist: true , destination: "data/{name}"});
project.addAssets("car_d.png", { notinlist: true , destination: "data/{name}"});
project.addAssets("ground.png", { notinlist: true , destination: "data/{name}"});
project.addAssets("home1.png", { notinlist: true , destination: "data/{name}"});
project.addAssets("home2.png", { notinlist: true , destination: "data/{name}"});
project.addAssets("home3.png", { notinlist: true , destination: "data/{name}"});
project.addAssets("home4.png", { notinlist: true , destination: "data/{name}"});
project.addAssets("home5.png", { notinlist: true , destination: "data/{name}"});
project.addAssets("police_d.png", { notinlist: true , destination: "data/{name}"});
project.addAssets("terrain.png", { notinlist: true , destination: "data/{name}"});
project.addAssets("w_d.png", { notinlist: true , destination: "data/{name}"});
project.addDefine('arm_hosek');
project.addDefine('arm_no_shadows');
project.addDefine('rp_renderer=Forward');
project.addDefine('rp_background=World');
project.addDefine('rp_gi=Off');
project.addDefine('rp_ssgi=Off');
project.addDefine('rp_gbuffer2');
project.addDefine('rp_gbuffer2_direct');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_published');
project.addDefine('arm_data_dir');
project.addDefine('arm_soundcompress');
project.addDefine('arm_skin');
project.addDefine('arm_particles_gpu');
project.addDefine('arm_particles');
project.addDefine('arm_config');
project.addDefine('arm_loadscreen');
project.addDefine('arm_fast');


resolve(project);
